name: nekoflow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  better_player: ^0.0.84
  cached_network_image: ^3.4.1
  crystal_navigation_bar: ^1.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.15
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  hugeicons: ^0.0.7
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/onboarding/
    - lib/assets/images/onboarding/logo.svg
    - lib/assets/images/profile/
    # - assets/images/home/
    # - assets/icons/app_icon.png